services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./html:/usr/share/nginx/html
      - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    networks:
      - reverse-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - ./acme:/etc/acme.sh
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    depends_on: 
      - nginx-proxy
    networks:
      - reverse-proxy
      
networks:
  reverse-proxy:
    external: true